### ISSUE TITLE
[analyzer] panda error

### ISSUE THREAD

**Issue by bitcoinsfacil** [bitphage/bitshares-tradehistory-analyzer#4]
Ubuntu 18.04.2 LTS (GNU/Linux 4.15.0-1036-gcp x86_64)

```
INFO    : Depositing 1000.00000000 BTS at Bitshares (2019-07-16 10:24:42+00:00, fee: 0.00000000 )
WARNING : Depositing more money (1000.0 BTS) than was withdrawn before (0.0 BTS). Assuming the additional amount (1000.0 BTS) was bought with 0 BRIDGE.YCE.
Traceback (most recent call last):
  File "./analyzer.py", line 140, in <module>
    main()
  File "./analyzer.py", line 93, in main
    log_bags(bf)
  File "./analyzer.py", line 38, in log_bags
    logger.info("State of bags: \n%s\n", '    ' + '\n    '.join(str(bags).split('\n')))
  File "/home/pedro/.local/share/virtualenvs/analyzerBitfag-U9Q01rFi/lib/python3.6/site-packages/ccgains/bags.py", line 388, in __str__
    return self.to_data_frame().to_string(
  File "/home/pedro/.local/share/virtualenvs/analyzerBitfag-U9Q01rFi/lib/python3.6/site-packages/ccgains/bags.py", line 385, in to_data_frame
    axis='columns')
  File "/home/pedro/.local/share/virtualenvs/analyzerBitfag-U9Q01rFi/lib/python3.6/site-packages/pandas/util/_decorators.py", line 221, in wrapper
    return func(*args, **kwargs)
  File "/home/pedro/.local/share/virtualenvs/analyzerBitfag-U9Q01rFi/lib/python3.6/site-packages/pandas/core/generic.py", line 1329, in rename_axis
    raise ValueError("Use `.rename` to alter labels " "with a mapper.")
ValueError: Use `.rename` to alter labels with a mapper.
```

No error on output ccgains_20190719-233032.log

**Comment by ds-voting** [comment]
Having same issue.

**Comment by bitphage** [comment]
This is a problem in ccgains https://github.com/probstj/ccGains/issues/28
ccgains doesn't have a strict version pinning, so I added manual pin to `pandas==0.24.2`.

`pipenv install` should install a proper version now.
